# Generated by Django 4.0.4 on 2022-06-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/uploads/')),
                ('heading', models.CharField(max_length=100)),
                ('discription', models.TextField()),
            ],
        ),
    ]
