# Generated by Django 4.0.4 on 2022-06-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plum', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
    ]
