# Generated by Django 4.0.4 on 2022-07-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plum', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(default=False, max_length=40),
        ),
    ]
