# Generated by Django 4.0.6 on 2022-07-23 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plum', '0007_alter_cart_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='addtocart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plum.category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plum.stform')),
            ],
        ),
    ]
